-- Codegen experiment (docs/web2-migration-design.md's "Codegen Experiment"
-- section): this schema was generated by scripts/codegen/genSql.ts directly
-- from daml/Vetify/Governance.daml's five registry templates
-- (AuthorizedOfficer, PolicyApprover, AuthorizedAssessor, AuthorizedSentinel,
-- AuthorizedAdvisor), then hand-adjusted in one place: the generator emitted
-- a self-access RLS clause keyed on `app.current_party_id` (matching Daml's
-- per-Party observer field on AuthorizedAssessor/Sentinel/Advisor exactly)
-- -- but this system's SessionContext has no per-individual party identity,
-- only a shared role per party type (see CLAUDE.md's "many users share one
-- Canton party" note) -- so that clause would always evaluate to false
-- (current_setting returns NULL) and contribute nothing. Simplified to a
-- blanket per-role check instead, consistent with every other registry-
-- shaped table already in this schema.

ALTER TABLE users DROP CONSTRAINT users_party_role_check;
ALTER TABLE users ADD CONSTRAINT users_party_role_check
  CHECK (party_role IN ('business', 'vetify', 'verifier', 'assessor', 'financialInstitution', 'advisor', 'sentinel'));

-- ─── AuthorizedOfficer ──────────────────────────────────────────────────────

CREATE TABLE authorized_officer (
  id BIGSERIAL PRIMARY KEY,
  officer_id TEXT NOT NULL,
  officer_name TEXT NOT NULL,
  roles JSONB NOT NULL,
  authorized_by TEXT NOT NULL,
  authorized_at TIMESTAMPTZ NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  approval_limit NUMERIC CHECK (approval_limit IS NULL OR approval_limit > 0),
  last_updated_by TEXT,
  last_updated_at TIMESTAMPTZ,
  status_reason TEXT,
  archived_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE authorized_officer ENABLE ROW LEVEL SECURITY;
ALTER TABLE authorized_officer FORCE ROW LEVEL SECURITY;

CREATE POLICY authorized_officer_select ON authorized_officer
  FOR SELECT USING (current_setting('app.current_party_role', true) IN ('vetify', 'financialInstitution'));

CREATE POLICY authorized_officer_insert ON authorized_officer
  FOR INSERT WITH CHECK (current_setting('app.current_party_role', true) = 'financialInstitution');

CREATE POLICY authorized_officer_update ON authorized_officer
  FOR UPDATE
  USING (current_setting('app.current_party_role', true) = 'financialInstitution')
  WITH CHECK (current_setting('app.current_party_role', true) = 'financialInstitution');

CREATE TRIGGER trg_authorized_officer_history
  AFTER UPDATE ON authorized_officer FOR EACH ROW EXECUTE FUNCTION record_entity_history();

-- ─── PolicyApprover ─────────────────────────────────────────────────────────

CREATE TABLE policy_approver (
  id BIGSERIAL PRIMARY KEY,
  approver_name TEXT NOT NULL,
  role TEXT NOT NULL,
  authorized_by TEXT NOT NULL,
  authorized_at TIMESTAMPTZ NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  archived_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE policy_approver ENABLE ROW LEVEL SECURITY;
ALTER TABLE policy_approver FORCE ROW LEVEL SECURITY;

CREATE POLICY policy_approver_select ON policy_approver
  FOR SELECT USING (current_setting('app.current_party_role', true) = 'vetify');

CREATE POLICY policy_approver_insert ON policy_approver
  FOR INSERT WITH CHECK (current_setting('app.current_party_role', true) = 'vetify');

CREATE POLICY policy_approver_update ON policy_approver
  FOR UPDATE
  USING (current_setting('app.current_party_role', true) = 'vetify')
  WITH CHECK (current_setting('app.current_party_role', true) = 'vetify');

CREATE TRIGGER trg_policy_approver_history
  AFTER UPDATE ON policy_approver FOR EACH ROW EXECUTE FUNCTION record_entity_history();

-- ─── AuthorizedAssessor ─────────────────────────────────────────────────────

CREATE TABLE authorized_assessor (
  id BIGSERIAL PRIMARY KEY,
  assessor TEXT NOT NULL,
  role TEXT NOT NULL,
  authorized_by TEXT NOT NULL,
  authorized_at TIMESTAMPTZ NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  archived_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE authorized_assessor ENABLE ROW LEVEL SECURITY;
ALTER TABLE authorized_assessor FORCE ROW LEVEL SECURITY;

CREATE POLICY authorized_assessor_select ON authorized_assessor
  FOR SELECT USING (current_setting('app.current_party_role', true) IN ('vetify', 'assessor'));

CREATE POLICY authorized_assessor_insert ON authorized_assessor
  FOR INSERT WITH CHECK (current_setting('app.current_party_role', true) = 'vetify');

CREATE POLICY authorized_assessor_update ON authorized_assessor
  FOR UPDATE
  USING (current_setting('app.current_party_role', true) = 'vetify')
  WITH CHECK (current_setting('app.current_party_role', true) = 'vetify');

CREATE TRIGGER trg_authorized_assessor_history
  AFTER UPDATE ON authorized_assessor FOR EACH ROW EXECUTE FUNCTION record_entity_history();

-- ─── AuthorizedSentinel ─────────────────────────────────────────────────────

CREATE TABLE authorized_sentinel (
  id BIGSERIAL PRIMARY KEY,
  sentinel TEXT NOT NULL,
  role TEXT NOT NULL,
  authorized_by TEXT NOT NULL,
  authorized_at TIMESTAMPTZ NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  archived_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE authorized_sentinel ENABLE ROW LEVEL SECURITY;
ALTER TABLE authorized_sentinel FORCE ROW LEVEL SECURITY;

CREATE POLICY authorized_sentinel_select ON authorized_sentinel
  FOR SELECT USING (current_setting('app.current_party_role', true) IN ('vetify', 'sentinel'));

CREATE POLICY authorized_sentinel_insert ON authorized_sentinel
  FOR INSERT WITH CHECK (current_setting('app.current_party_role', true) = 'vetify');

CREATE POLICY authorized_sentinel_update ON authorized_sentinel
  FOR UPDATE
  USING (current_setting('app.current_party_role', true) = 'vetify')
  WITH CHECK (current_setting('app.current_party_role', true) = 'vetify');

CREATE TRIGGER trg_authorized_sentinel_history
  AFTER UPDATE ON authorized_sentinel FOR EACH ROW EXECUTE FUNCTION record_entity_history();

-- ─── AuthorizedAdvisor ──────────────────────────────────────────────────────

CREATE TABLE authorized_advisor (
  id BIGSERIAL PRIMARY KEY,
  advisor TEXT NOT NULL,
  role TEXT NOT NULL,
  authorized_by TEXT NOT NULL,
  authorized_at TIMESTAMPTZ NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  archived_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE authorized_advisor ENABLE ROW LEVEL SECURITY;
ALTER TABLE authorized_advisor FORCE ROW LEVEL SECURITY;

CREATE POLICY authorized_advisor_select ON authorized_advisor
  FOR SELECT USING (current_setting('app.current_party_role', true) IN ('vetify', 'advisor'));

CREATE POLICY authorized_advisor_insert ON authorized_advisor
  FOR INSERT WITH CHECK (current_setting('app.current_party_role', true) = 'vetify');

CREATE POLICY authorized_advisor_update ON authorized_advisor
  FOR UPDATE
  USING (current_setting('app.current_party_role', true) = 'vetify')
  WITH CHECK (current_setting('app.current_party_role', true) = 'vetify');

CREATE TRIGGER trg_authorized_advisor_history
  AFTER UPDATE ON authorized_advisor FOR EACH ROW EXECUTE FUNCTION record_entity_history();
