/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserId = IDL.Principal;
export const RegistrationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'underReview' : IDL.Null,
  'financingReady' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'kycInProgress' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Timestamp = IDL.Int;
export const RiskLevel = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const MizanStage = IDL.Variant({
  'full' : IDL.Null,
  'preliminary' : IDL.Null,
});
export const MizanRecord = IDL.Record({
  'halalComplianceScore' : IDL.Nat,
  'narrativeSummary' : IDL.Text,
  'computedAt' : Timestamp,
  'incomeStabilityScore' : IDL.Nat,
  'riskClassification' : RiskLevel,
  'overallReadinessScore' : IDL.Nat,
  'debtBehaviorScore' : IDL.Nat,
  'stage' : MizanStage,
  'repaymentPatternScore' : IDL.Nat,
  'revenueTrendScore' : IDL.Nat,
  'isBorderline' : IDL.Bool,
  'borderlineReasons' : IDL.Vec(IDL.Text),
});
export const ProprietorRecord = IDL.Record({
  'bvn' : IDL.Text,
  'nin' : IDL.Text,
  'proprietorName' : IDL.Text,
});
export const BusinessTypeEnum = IDL.Variant({
  'llc' : IDL.Null,
  'businessName' : IDL.Null,
});
export const InconsistencyFlag = IDL.Record({
  'field' : IDL.Text,
  'verifiedValue' : IDL.Text,
  'declaredValue' : IDL.Text,
});
export const CreditReadinessVerdict = IDL.Variant({
  'conditionalReady' : IDL.Null,
  'notReady' : IDL.Null,
  'ready' : IDL.Null,
});
export const ShariaFlag = IDL.Record({
  'indicator' : IDL.Text,
  'category' : IDL.Text,
  'severity' : IDL.Variant({ 'major' : IDL.Null, 'minor' : IDL.Null }),
});
export const TawthiqRecord = IDL.Record({
  'completedAt' : IDL.Opt(Timestamp),
  'narrativeSummary' : IDL.Text,
  'inconsistencyFlags' : IDL.Vec(InconsistencyFlag),
  'creditReadinessVerdict' : CreditReadinessVerdict,
  'shariaScreeningStatus' : IDL.Variant({
    'Failed' : IDL.Null,
    'Passed' : IDL.Null,
    'Pending' : IDL.Null,
  }),
  'inconsistencyStatus' : IDL.Variant({
    'Flagged' : IDL.Null,
    'Clean' : IDL.Null,
    'Pending' : IDL.Null,
  }),
  'shariaFlags' : IDL.Vec(ShariaFlag),
  'shariaScreeningNotes' : IDL.Text,
});
export const ScoringRecord = IDL.Record({
  'halalComplianceScore' : IDL.Nat,
  'scoredAt' : Timestamp,
  'scoringNotes' : IDL.Text,
  'financingReadinessScore' : IDL.Nat,
  'riskLevel' : RiskLevel,
});
export const HalalComplianceStatus = IDL.Variant({
  'pending' : IDL.Null,
  'compliant' : IDL.Null,
  'flagged' : IDL.Null,
});
export const KycStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'InProgress' : IDL.Null,
  'Verified' : IDL.Null,
  'Pending' : IDL.Null,
});
export const KycCheckRecord = IDL.Record({
  'watchlistClean' : IDL.Bool,
  'cacVerified' : IDL.Bool,
  'watchlistParseError' : IDL.Bool,
  'kycStatus' : KycStatus,
  'creditScore' : IDL.Nat,
  'bvnVerified' : IDL.Bool,
  'ninVerified' : IDL.Bool,
  'tinVerified' : IDL.Bool,
  'verifiedAt' : IDL.Opt(Timestamp),
});
export const BankLinkStatus = IDL.Variant({
  'NotLinked' : IDL.Null,
  'Linked' : IDL.Null,
  'LinkFailed' : IDL.Text,
});
export const TransactionSummary = IDL.Record({
  'totalDebits' : IDL.Nat,
  'income' : IDL.Nat,
  'totalCredits' : IDL.Nat,
  'months' : IDL.Nat,
});
export const BankLinkRecord = IDL.Record({
  'status' : BankLinkStatus,
  'linkedAt' : IDL.Opt(Timestamp),
  'transactionSummary' : IDL.Opt(TransactionSummary),
  'balance' : IDL.Opt(IDL.Nat),
  'accountId' : IDL.Opt(IDL.Text),
  'institutionName' : IDL.Opt(IDL.Text),
  'currency' : IDL.Opt(IDL.Text),
});
export const RiskLevel__1 = IDL.Variant({
  'low' : IDL.Null,
  'pending' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const DirectorRecord = IDL.Record({
  'bvn' : IDL.Text,
  'nin' : IDL.Text,
  'nationality' : IDL.Text,
  'directorName' : IDL.Text,
  'ownershipPercentage' : IDL.Float64,
});
export const BusinessProfile = IDL.Record({
  'mizanRecord' : IDL.Opt(MizanRecord),
  'cacNumber' : IDL.Text,
  'proprietorDetails' : IDL.Opt(ProprietorRecord),
  'businessTypeEnum' : IDL.Opt(BusinessTypeEnum),
  'financingAmountSought' : IDL.Opt(IDL.Nat),
  'purposeOfFinancing' : IDL.Opt(IDL.Text),
  'userId' : UserId,
  'tawthiqRecord' : IDL.Opt(TawthiqRecord),
  'createdAt' : Timestamp,
  'scoringRecord' : ScoringRecord,
  'halalComplianceStatus' : HalalComplianceStatus,
  'contactPerson' : IDL.Text,
  'preliminaryMizanRecord' : IDL.Opt(MizanRecord),
  'businessName' : IDL.Text,
  'businessType' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'financingReady' : IDL.Bool,
  'financingReadyScore' : IDL.Nat,
  'preferredInstrument' : IDL.Opt(IDL.Text),
  'kycRecord' : KycCheckRecord,
  'yearOfIncorporation' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'businessDescription' : IDL.Opt(IDL.Text),
  'registrationStatus' : RegistrationStatus,
  'bankLinkRecord' : BankLinkRecord,
  'mizanDivergenceAlert' : IDL.Bool,
  'riskLevel' : RiskLevel__1,
  'annualRevenue' : IDL.Nat,
  'directorsList' : IDL.Opt(IDL.Vec(DirectorRecord)),
});
export const UploadStatus = IDL.Variant({
  'uploaded' : IDL.Null,
  'notUploaded' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DocumentType = IDL.Variant({
  'cacCertificate' : IDL.Null,
  'bankStatement' : IDL.Null,
  'governmentId' : IDL.Null,
});
export const DocumentRecord = IDL.Record({
  'uploadStatus' : UploadStatus,
  'userId' : UserId,
  'storageRef' : IDL.Opt(ExternalBlob),
  'docType' : DocumentType,
  'uploadedAt' : IDL.Opt(Timestamp),
});
export const IndividualMizanRecord = IDL.Record({
  'completedAt' : IDL.Opt(Timestamp),
  'narrativeSummary' : IDL.Text,
  'overallScore' : IDL.Nat,
  'incomeStabilityScore' : IDL.Nat,
  'debtBehaviorScore' : IDL.Nat,
  'stage' : IDL.Variant({ 'full' : IDL.Null, 'preliminary' : IDL.Null }),
  'borderlineFlag' : IDL.Bool,
  'repaymentCapacityScore' : IDL.Nat,
  'riskLevel' : RiskLevel__1,
});
export const IndividualTawthiqRecord = IDL.Record({
  'completedAt' : IDL.Opt(Timestamp),
  'watchlistClean' : IDL.Bool,
  'narrativeSummary' : IDL.Text,
  'creditReadiness' : IDL.Variant({
    'conditionalReady' : IDL.Null,
    'notReady' : IDL.Null,
    'ready' : IDL.Null,
  }),
  'shariaComplianceScore' : IDL.Nat,
  'bvnVerified' : IDL.Bool,
  'ninVerified' : IDL.Bool,
  'shariaFlags' : IDL.Vec(IDL.Text),
  'incomeAnalysis' : IDL.Text,
});
export const IncomeSource = IDL.Variant({
  'other' : IDL.Null,
  'employment' : IDL.Null,
  'selfEmployment' : IDL.Null,
  'business' : IDL.Null,
});
export const PreferredInstrument = IDL.Variant({
  'murabaha' : IDL.Null,
  'istisna' : IDL.Null,
  'other' : IDL.Null,
  'ijarah' : IDL.Null,
  'salam' : IDL.Null,
  'musharakah' : IDL.Null,
  'mudarabah' : IDL.Null,
});
export const EmploymentStatus = IDL.Variant({
  'unemployed' : IDL.Null,
  'employed' : IDL.Null,
  'student' : IDL.Null,
  'selfEmployed' : IDL.Null,
});
export const FinancingPurpose = IDL.Variant({
  'other' : IDL.Null,
  'education' : IDL.Null,
  'startupCapital' : IDL.Null,
  'homePurchase' : IDL.Null,
  'vehicle' : IDL.Null,
  'medical' : IDL.Null,
});
export const IndividualProfile = IDL.Record({
  'id' : UserId,
  'bvn' : IDL.Text,
  'nin' : IDL.Text,
  'mizanRecord' : IDL.Opt(IndividualMizanRecord),
  'occupation' : IDL.Text,
  'termsAcceptedAt' : IDL.Opt(Timestamp),
  'financingPurposeOther' : IDL.Opt(IDL.Text),
  'dateOfBirth' : IDL.Text,
  'tawthiqRecord' : IDL.Opt(IndividualTawthiqRecord),
  'createdAt' : Timestamp,
  'incomeSource' : IncomeSource,
  'fullName' : IDL.Text,
  'accountClosureRequestedAt' : IDL.Opt(Timestamp),
  'photoUrl' : IDL.Opt(IDL.Text),
  'amountSought' : IDL.Nat,
  'preferredInstrument' : PreferredInstrument,
  'kycRecord' : IDL.Opt(KycCheckRecord),
  'updatedAt' : Timestamp,
  'employerName' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'employmentStatus' : EmploymentStatus,
  'registrationStatus' : RegistrationStatus,
  'bankLinkStatus' : BankLinkStatus,
  'financingPurpose' : FinancingPurpose,
  'accountClosureRequested' : IDL.Bool,
  'monthlyIncome' : IDL.Nat,
});
export const Result_5 = IDL.Variant({
  'ok' : IndividualProfile,
  'err' : IDL.Text,
});
export const KashifReportLog = IDL.Record({
  'businessId' : IDL.Principal,
  'generatedAt' : IDL.Int,
  'viewCount' : IDL.Nat,
  'lastViewedAt' : IDL.Opt(IDL.Int),
});
export const BusinessPage = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(BusinessProfile),
});
export const FinancierType = IDL.Variant({
  'institution' : IDL.Null,
  'group' : IDL.Null,
  'individual' : IDL.Null,
});
export const InstitutionDetails = IDL.Record({
  'riskAppetite' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'preferredInstruments' : IDL.Vec(PreferredInstrument),
  'ticketSizeMax' : IDL.Nat,
  'ticketSizeMin' : IDL.Nat,
});
export const GroupDetails = IDL.Record({
  'numberOfMembers' : IDL.Nat,
  'leadContactBvn' : IDL.Text,
  'leadContactNin' : IDL.Text,
  'combinedInvestmentCapacity' : IDL.Nat,
  'legalBasis' : IDL.Text,
  'riskAppetite' : IDL.Text,
  'preferredInstruments' : IDL.Vec(PreferredInstrument),
  'leadContactName' : IDL.Text,
  'groupName' : IDL.Text,
});
export const IndividualDetails = IDL.Record({
  'bvn' : IDL.Text,
  'nin' : IDL.Text,
  'occupation' : IDL.Text,
  'investmentCapacity' : IDL.Nat,
  'fullName' : IDL.Text,
  'riskAppetite' : IDL.Text,
  'preferredInstruments' : IDL.Vec(PreferredInstrument),
});
export const FinancierStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
  'PendingReview' : IDL.Null,
});
export const FinancierProfile = IDL.Record({
  'financierType' : IDL.Opt(FinancierType),
  'institutionDetails' : IDL.Opt(InstitutionDetails),
  'groupDetails' : IDL.Opt(GroupDetails),
  'institutionName' : IDL.Text,
  'individualDetails' : IDL.Opt(IndividualDetails),
  'userId' : UserId,
  'createdAt' : Timestamp,
  'contactPerson' : IDL.Text,
  'areasOfFinancing' : IDL.Vec(IDL.Text),
  'photoUrl' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'financierStatus' : FinancierStatus,
  'licenseNumber' : IDL.Text,
  'phone' : IDL.Text,
  'registrationStatus' : RegistrationStatus,
});
export const FinancierPage = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(FinancierProfile),
});
export const IndividualSummary = IDL.Record({
  'id' : UserId,
  'createdAt' : Timestamp,
  'fullName' : IDL.Text,
  'amountSought' : IDL.Nat,
  'registrationStatus' : RegistrationStatus,
  'financingPurpose' : FinancingPurpose,
  'riskLevel' : RiskLevel__1,
});
export const Result_8 = IDL.Variant({
  'ok' : IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(IndividualSummary),
  }),
  'err' : IDL.Text,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const AccountClosureRequest = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'applicantType' : IDL.Variant({
    'business' : IDL.Null,
    'financier' : IDL.Null,
    'individual' : IDL.Null,
  }),
  'requestId' : IDL.Text,
  'processedAt' : IDL.Opt(Timestamp),
  'adminNote' : IDL.Opt(IDL.Text),
  'principalId' : UserId,
  'requestedAt' : Timestamp,
});
export const Result_7 = IDL.Variant({
  'ok' : IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(AccountClosureRequest),
  }),
  'err' : IDL.Text,
});
export const AdminAnalytics = IDL.Record({
  'averageMizanScore' : IDL.Nat,
  'closedDealsCount' : IDL.Nat,
  'financingReadyCount' : IDL.Nat,
  'tawthiqPassCount' : IDL.Nat,
  'pendingReviewCount' : IDL.Nat,
  'totalFinanciers' : IDL.Nat,
  'totalIndividuals' : IDL.Nat,
  'tawthiqConditionalCount' : IDL.Nat,
  'tawthiqFailCount' : IDL.Nat,
  'activeFinancierCount' : IDL.Nat,
  'totalBusinesses' : IDL.Nat,
});
export const Result_6 = IDL.Variant({
  'ok' : AdminAnalytics,
  'err' : IDL.Text,
});
export const AuditEntry = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'oldValue' : IDL.Opt(IDL.Text),
  'changedBy' : IDL.Text,
  'newValue' : IDL.Opt(IDL.Text),
  'entityId' : IDL.Text,
  'timestamp' : Timestamp,
  'entityType' : IDL.Text,
  'reason' : IDL.Opt(IDL.Text),
});
export const AuditPage = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'entries' : IDL.Vec(AuditEntry),
});
export const ApplicantType = IDL.Variant({
  'business' : IDL.Null,
  'individual' : IDL.Null,
});
export const CompatibilityResult = IDL.Record({
  'halalComplianceScore' : IDL.Nat,
  'applicantType' : ApplicantType,
  'compatibilityScore' : IDL.Nat,
  'businessCategory' : IDL.Text,
  'displayName' : IDL.Text,
  'businessId' : IDL.Principal,
  'financingTypes' : IDL.Vec(IDL.Text),
  'riskLevel' : RiskLevel,
});
export const MaskedCredentials = IDL.Record({
  'monoSecretKey' : IDL.Text,
  'twilioAuthToken' : IDL.Text,
  'twilioAccountSid' : IDL.Text,
  'openAiApiKey' : IDL.Text,
  'twilioWhatsappFrom' : IDL.Text,
});
export const DealReport = IDL.Record({
  'applicantType' : ApplicantType,
  'creditReadiness' : IDL.Text,
  'compatibilityScore' : IDL.Nat,
  'financingRecommendation' : IDL.Text,
  'riskBreakdown' : IDL.Text,
  'generatedAt' : IDL.Int,
  'mizanVersion' : IDL.Int,
  'executiveSummary' : IDL.Text,
  'tawthiqVersion' : IDL.Int,
  'financialHighlights' : IDL.Text,
  'suggestedFinancingStructure' : IDL.Text,
  'shariahComplianceStatus' : IDL.Text,
});
export const KashifScoringConfig = IDL.Record({
  'riskKeywords' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'instrumentWeights' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'defaultScore' : IDL.Nat,
});
export const NotificationRecord = IDL.Record({
  'statusChange' : IDL.Text,
  'recipientPhone' : IDL.Text,
  'sentAt' : Timestamp,
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const Result_4 = IDL.Variant({
  'ok' : IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(NotificationRecord),
  }),
  'err' : IDL.Text,
});
export const AppealStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const TawthiqAppeal = IDL.Record({
  'id' : IDL.Text,
  'status' : AppealStatus,
  'documentName' : IDL.Opt(IDL.Text),
  'documentUrl' : IDL.Opt(IDL.Text),
  'adminPrincipal' : IDL.Opt(IDL.Principal),
  'businessId' : UserId,
  'flagId' : IDL.Text,
  'submittedAt' : Timestamp,
  'reviewedAt' : IDL.Opt(Timestamp),
  'adminNote' : IDL.Opt(IDL.Text),
  'appealText' : IDL.Text,
});
export const PipelineStage = IDL.Variant({
  'dueDiligence' : IDL.Null,
  'closed' : IDL.Null,
  'offerSent' : IDL.Null,
  'reviewing' : IDL.Null,
});
export const ShortlistEntry = IDL.Record({
  'businessId' : IDL.Principal,
  'addedAt' : IDL.Int,
});
export const TawthiqOverviewStats = IDL.Record({
  'pendingCount' : IDL.Nat,
  'conditionalCount' : IDL.Nat,
  'totalProcessed' : IDL.Nat,
  'notReadyCount' : IDL.Nat,
  'passedCount' : IDL.Nat,
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const Message = IDL.Record({
  'applicantId' : IDL.Text,
  'messageId' : IDL.Nat,
  'isRead' : IDL.Bool,
  'messageText' : IDL.Text,
  'timestamp' : IDL.Int,
  'financierId' : IDL.Text,
  'recipientId' : IDL.Principal,
  'senderId' : IDL.Principal,
});
export const DirectMessageThread = IDL.Record({
  'lastMessageAt' : IDL.Int,
  'messages' : IDL.Vec(Message),
  'participantIds' : IDL.Vec(IDL.Principal),
  'threadId' : IDL.Text,
});
export const ProfilePrivacySettings = IDL.Record({
  'applicantId' : IDL.Text,
  'showFinancingAmount' : IDL.Bool,
  'showMizanScore' : IDL.Bool,
  'showDirectorNames' : IDL.Bool,
  'showIncome' : IDL.Bool,
});
export const PublicApplicantProfile = IDL.Record({
  'applicantId' : IDL.Text,
  'fullName' : IDL.Text,
  'amountSought' : IDL.Opt(IDL.Nat),
  'mizanScore' : IDL.Opt(IDL.Nat),
  'preferredInstrument' : IDL.Text,
  'registrationStatus' : IDL.Text,
  'financingPurpose' : IDL.Text,
  'monthlyIncome' : IDL.Opt(IDL.Nat),
});
export const InviteLinkRecord = IDL.Record({
  'status' : IDL.Text,
  'expiresAt' : IDL.Int,
  'code' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'financier' : IDL.Null,
  'businessApplicant' : IDL.Null,
});
export const ApplicantSummary = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : UserId,
  'role' : UserRole,
  'halalComplianceStatus' : HalalComplianceStatus,
  'financingReady' : IDL.Bool,
  'financingReadyScore' : IDL.Nat,
  'riskLevel' : RiskLevel__1,
});
export const Page = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(ApplicantSummary),
});
export const Result_3 = IDL.Variant({
  'ok' : IDL.Record({
    'status' : RegistrationStatus,
    'tawthiqDone' : IDL.Bool,
    'mizanDone' : IDL.Bool,
  }),
  'err' : IDL.Text,
});
export const CredentialsSettings = IDL.Record({
  'monoSecretKey' : IDL.Text,
  'twilioAuthToken' : IDL.Text,
  'twilioAccountSid' : IDL.Text,
  'openAiApiKey' : IDL.Text,
  'twilioWhatsappFrom' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const BusinessProfileUpdate = IDL.Record({
  'contactPerson' : IDL.Opt(IDL.Text),
  'businessName' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adminChangeIndividualStatus' : IDL.Func(
      [UserId, RegistrationStatus],
      [Result],
      [],
    ),
  'adminGetBusiness' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(BusinessProfile)],
      [],
    ),
  'adminGetDocumentsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DocumentRecord)],
      [],
    ),
  'adminGetIndividual' : IDL.Func([UserId], [Result_5], []),
  'adminGetKashifLogs' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Record({ 'total' : IDL.Nat, 'items' : IDL.Vec(KashifReportLog) })],
      [],
    ),
  'adminListBusinesses' : IDL.Func([IDL.Nat, IDL.Nat], [BusinessPage], []),
  'adminListFinanciers' : IDL.Func([IDL.Nat, IDL.Nat], [FinancierPage], []),
  'adminListIndividuals' : IDL.Func([IDL.Nat, IDL.Nat], [Result_8], ['query']),
  'adminProcessAccountClosure' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Text],
      [Result],
      [],
    ),
  'adminSetFinancingReady' : IDL.Func(
      [IDL.Principal, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'adminSetIndividualFinancingReady' : IDL.Func([UserId], [Result], []),
  'adminTriggerReportRegeneration' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'bootstrapAdmin' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'generateAdminInviteLink' : IDL.Func([], [Result_1], []),
  'getAccountClosureRequests' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [Result_7],
      ['query'],
    ),
  'getAdminAnalytics' : IDL.Func([], [Result_6], ['query']),
  'getAdminCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAuditLog' : IDL.Func([IDL.Nat, IDL.Nat], [AuditPage], ['query']),
  'getAuditLogForEntity' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [AuditPage],
      ['query'],
    ),
  'getBootstrapAdmin' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getComparisonData' : IDL.Func(
      [IDL.Vec(IDL.Principal)],
      [IDL.Variant({ 'ok' : IDL.Vec(CompatibilityResult), 'err' : IDL.Text })],
      [],
    ),
  'getCredentials' : IDL.Func([], [MaskedCredentials], ['query']),
  'getCycleBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getDealReport' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : DealReport, 'err' : IDL.Text })],
      [],
    ),
  'getDocumentsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DocumentRecord)],
      ['query'],
    ),
  'getFinancingReadyBusiness' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(BusinessProfile)],
      ['query'],
    ),
  'getKashifScoringConfig' : IDL.Func([], [KashifScoringConfig], ['query']),
  'getMatchedBorrowers' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'items' : IDL.Vec(CompatibilityResult),
        }),
      ],
      [],
    ),
  'getMizanResult' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : MizanRecord, 'err' : IDL.Text })],
      ['query'],
    ),
  'getMockCycleBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
  'getMyDocument' : IDL.Func(
      [DocumentType],
      [IDL.Opt(DocumentRecord)],
      ['query'],
    ),
  'getMyFinancierProfile' : IDL.Func(
      [],
      [IDL.Opt(FinancierProfile)],
      ['query'],
    ),
  'getMyIndividualProfile' : IDL.Func([], [Result_5], ['query']),
  'getMyNotifications' : IDL.Func([IDL.Nat, IDL.Nat], [Result_4], ['query']),
  'getMyTawthiqAppeals' : IDL.Func([], [IDL.Vec(TawthiqAppeal)], ['query']),
  'getPipeline' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, PipelineStage))],
      ['query'],
    ),
  'getPreliminaryMizanByBusiness' : IDL.Func(
      [UserId],
      [IDL.Opt(MizanRecord)],
      ['query'],
    ),
  'getPreliminaryMizanResult' : IDL.Func([], [IDL.Opt(MizanRecord)], ['query']),
  'getProfilePhoto' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'getShortlist' : IDL.Func([], [IDL.Vec(ShortlistEntry)], []),
  'getStableStateVersion' : IDL.Func([], [IDL.Nat], ['query']),
  'getTawthiqAdminNote' : IDL.Func([UserId], [IDL.Opt(IDL.Text)], ['query']),
  'getTawthiqAppeals' : IDL.Func([UserId], [IDL.Vec(TawthiqAppeal)], ['query']),
  'getTawthiqCompletedAssessments' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [
        IDL.Record({
          'page' : IDL.Nat,
          'totalCount' : IDL.Nat,
          'pageSize' : IDL.Nat,
          'items' : IDL.Vec(BusinessProfile),
        }),
      ],
      ['query'],
    ),
  'getTawthiqOverviewStats' : IDL.Func([], [TawthiqOverviewStats], ['query']),
  'getTawthiqPendingReviews' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [
        IDL.Record({
          'page' : IDL.Nat,
          'totalCount' : IDL.Nat,
          'pageSize' : IDL.Nat,
          'items' : IDL.Vec(BusinessProfile),
        }),
      ],
      ['query'],
    ),
  'getTawthiqRecord' : IDL.Func([UserId], [IDL.Opt(TawthiqRecord)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [Result_2], ['query']),
  'get_my_threads' : IDL.Func([], [IDL.Vec(DirectMessageThread)], ['query']),
  'get_privacy_settings' : IDL.Func(
      [IDL.Text],
      [ProfilePrivacySettings],
      ['query'],
    ),
  'get_public_profile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PublicApplicantProfile)],
      ['query'],
    ),
  'get_thread_messages' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'get_unread_count' : IDL.Func([], [IDL.Nat], ['query']),
  'isAdminBootstrapped' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkBankAccount' : IDL.Func([IDL.Text], [BusinessProfile], []),
  'listAdminInviteLinks' : IDL.Func([], [IDL.Vec(InviteLinkRecord)], ['query']),
  'listBorderlineBusinesses' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'total' : IDL.Nat, 'items' : IDL.Vec(ApplicantSummary) })],
      ['query'],
    ),
  'listFinancingReadyApplicants' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [Page],
      ['query'],
    ),
  'listMyDocuments' : IDL.Func([], [IDL.Vec(DocumentRecord)], ['query']),
  'markNotificationsRead' : IDL.Func([], [Result], []),
  'mark_messages_read' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'mockTopUp' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'pollIndividualStatus' : IDL.Func([], [Result_3], ['query']),
  'redeemAdminInviteLink' : IDL.Func([IDL.Text], [Result], []),
  'registerAsFinancier' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        FinancierType,
        IDL.Opt(InstitutionDetails),
        IDL.Opt(IndividualDetails),
        IDL.Opt(GroupDetails),
      ],
      [FinancierProfile],
      [],
    ),
  'removeFromShortlist' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'removePipelineEntry' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'requestAccountClosure' : IDL.Func([], [Result], []),
  'requestIndividualBankLink' : IDL.Func([], [Result_1], []),
  'reviewTawthiqAppeal' : IDL.Func(
      [UserId, IDL.Text, AppealStatus, IDL.Text],
      [IDL.Variant({ 'ok' : TawthiqAppeal, 'err' : IDL.Text })],
      [],
    ),
  'revokeAdminInviteLink' : IDL.Func([IDL.Text], [Result], []),
  'runAndStorePreliminaryMizan' : IDL.Func([IDL.Principal], [], []),
  'saveTawthiqAdminNote' : IDL.Func(
      [UserId, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'send_message' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Principal, IDL.Text],
      [Result_2],
      [],
    ),
  'setCredentials' : IDL.Func([CredentialsSettings], [], []),
  'setFinancierStatus' : IDL.Func(
      [IDL.Principal, FinancierStatus, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setPipelineStage' : IDL.Func(
      [IDL.Principal, PipelineStage],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setProfilePhoto' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'shortlistBorrower' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'submitBusinessRegistrationWithKyc' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(DirectorRecord),
        IDL.Opt(ProprietorRecord),
      ],
      [BusinessProfile],
      [],
    ),
  'submitIndividualRegistration' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        EmploymentStatus,
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IncomeSource,
        FinancingPurpose,
        IDL.Opt(IDL.Text),
        IDL.Nat,
        PreferredInstrument,
        IDL.Opt(Timestamp),
      ],
      [Result_1],
      [],
    ),
  'submitTawthiqAppeal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : TawthiqAppeal, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'triggerMizanAnalysis' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : MizanRecord, 'err' : IDL.Text })],
      [],
    ),
  'updateBusinessProfile' : IDL.Func(
      [IDL.Principal, BusinessProfileUpdate],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateBusinessStatus' : IDL.Func(
      [IDL.Principal, RegistrationStatus, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateIndividualProfile' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IncomeSource),
      ],
      [Result],
      [],
    ),
  'updateKashifScoringConfig' : IDL.Func(
      [KashifScoringConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateMyProfile' : IDL.Func(
      [BusinessProfileUpdate],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'update_privacy_settings' : IDL.Func(
      [IDL.Text, ProfilePrivacySettings],
      [Result],
      [],
    ),
  'uploadDocument' : IDL.Func(
      [DocumentType, ExternalBlob],
      [DocumentRecord],
      [],
    ),
  'validateAdminInviteLink' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserId = IDL.Principal;
  const RegistrationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'underReview' : IDL.Null,
    'financingReady' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'kycInProgress' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Timestamp = IDL.Int;
  const RiskLevel = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const MizanStage = IDL.Variant({
    'full' : IDL.Null,
    'preliminary' : IDL.Null,
  });
  const MizanRecord = IDL.Record({
    'halalComplianceScore' : IDL.Nat,
    'narrativeSummary' : IDL.Text,
    'computedAt' : Timestamp,
    'incomeStabilityScore' : IDL.Nat,
    'riskClassification' : RiskLevel,
    'overallReadinessScore' : IDL.Nat,
    'debtBehaviorScore' : IDL.Nat,
    'stage' : MizanStage,
    'repaymentPatternScore' : IDL.Nat,
    'revenueTrendScore' : IDL.Nat,
    'isBorderline' : IDL.Bool,
    'borderlineReasons' : IDL.Vec(IDL.Text),
  });
  const ProprietorRecord = IDL.Record({
    'bvn' : IDL.Text,
    'nin' : IDL.Text,
    'proprietorName' : IDL.Text,
  });
  const BusinessTypeEnum = IDL.Variant({
    'llc' : IDL.Null,
    'businessName' : IDL.Null,
  });
  const InconsistencyFlag = IDL.Record({
    'field' : IDL.Text,
    'verifiedValue' : IDL.Text,
    'declaredValue' : IDL.Text,
  });
  const CreditReadinessVerdict = IDL.Variant({
    'conditionalReady' : IDL.Null,
    'notReady' : IDL.Null,
    'ready' : IDL.Null,
  });
  const ShariaFlag = IDL.Record({
    'indicator' : IDL.Text,
    'category' : IDL.Text,
    'severity' : IDL.Variant({ 'major' : IDL.Null, 'minor' : IDL.Null }),
  });
  const TawthiqRecord = IDL.Record({
    'completedAt' : IDL.Opt(Timestamp),
    'narrativeSummary' : IDL.Text,
    'inconsistencyFlags' : IDL.Vec(InconsistencyFlag),
    'creditReadinessVerdict' : CreditReadinessVerdict,
    'shariaScreeningStatus' : IDL.Variant({
      'Failed' : IDL.Null,
      'Passed' : IDL.Null,
      'Pending' : IDL.Null,
    }),
    'inconsistencyStatus' : IDL.Variant({
      'Flagged' : IDL.Null,
      'Clean' : IDL.Null,
      'Pending' : IDL.Null,
    }),
    'shariaFlags' : IDL.Vec(ShariaFlag),
    'shariaScreeningNotes' : IDL.Text,
  });
  const ScoringRecord = IDL.Record({
    'halalComplianceScore' : IDL.Nat,
    'scoredAt' : Timestamp,
    'scoringNotes' : IDL.Text,
    'financingReadinessScore' : IDL.Nat,
    'riskLevel' : RiskLevel,
  });
  const HalalComplianceStatus = IDL.Variant({
    'pending' : IDL.Null,
    'compliant' : IDL.Null,
    'flagged' : IDL.Null,
  });
  const KycStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'InProgress' : IDL.Null,
    'Verified' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const KycCheckRecord = IDL.Record({
    'watchlistClean' : IDL.Bool,
    'cacVerified' : IDL.Bool,
    'watchlistParseError' : IDL.Bool,
    'kycStatus' : KycStatus,
    'creditScore' : IDL.Nat,
    'bvnVerified' : IDL.Bool,
    'ninVerified' : IDL.Bool,
    'tinVerified' : IDL.Bool,
    'verifiedAt' : IDL.Opt(Timestamp),
  });
  const BankLinkStatus = IDL.Variant({
    'NotLinked' : IDL.Null,
    'Linked' : IDL.Null,
    'LinkFailed' : IDL.Text,
  });
  const TransactionSummary = IDL.Record({
    'totalDebits' : IDL.Nat,
    'income' : IDL.Nat,
    'totalCredits' : IDL.Nat,
    'months' : IDL.Nat,
  });
  const BankLinkRecord = IDL.Record({
    'status' : BankLinkStatus,
    'linkedAt' : IDL.Opt(Timestamp),
    'transactionSummary' : IDL.Opt(TransactionSummary),
    'balance' : IDL.Opt(IDL.Nat),
    'accountId' : IDL.Opt(IDL.Text),
    'institutionName' : IDL.Opt(IDL.Text),
    'currency' : IDL.Opt(IDL.Text),
  });
  const RiskLevel__1 = IDL.Variant({
    'low' : IDL.Null,
    'pending' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const DirectorRecord = IDL.Record({
    'bvn' : IDL.Text,
    'nin' : IDL.Text,
    'nationality' : IDL.Text,
    'directorName' : IDL.Text,
    'ownershipPercentage' : IDL.Float64,
  });
  const BusinessProfile = IDL.Record({
    'mizanRecord' : IDL.Opt(MizanRecord),
    'cacNumber' : IDL.Text,
    'proprietorDetails' : IDL.Opt(ProprietorRecord),
    'businessTypeEnum' : IDL.Opt(BusinessTypeEnum),
    'financingAmountSought' : IDL.Opt(IDL.Nat),
    'purposeOfFinancing' : IDL.Opt(IDL.Text),
    'userId' : UserId,
    'tawthiqRecord' : IDL.Opt(TawthiqRecord),
    'createdAt' : Timestamp,
    'scoringRecord' : ScoringRecord,
    'halalComplianceStatus' : HalalComplianceStatus,
    'contactPerson' : IDL.Text,
    'preliminaryMizanRecord' : IDL.Opt(MizanRecord),
    'businessName' : IDL.Text,
    'businessType' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'financingReady' : IDL.Bool,
    'financingReadyScore' : IDL.Nat,
    'preferredInstrument' : IDL.Opt(IDL.Text),
    'kycRecord' : KycCheckRecord,
    'yearOfIncorporation' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'businessDescription' : IDL.Opt(IDL.Text),
    'registrationStatus' : RegistrationStatus,
    'bankLinkRecord' : BankLinkRecord,
    'mizanDivergenceAlert' : IDL.Bool,
    'riskLevel' : RiskLevel__1,
    'annualRevenue' : IDL.Nat,
    'directorsList' : IDL.Opt(IDL.Vec(DirectorRecord)),
  });
  const UploadStatus = IDL.Variant({
    'uploaded' : IDL.Null,
    'notUploaded' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DocumentType = IDL.Variant({
    'cacCertificate' : IDL.Null,
    'bankStatement' : IDL.Null,
    'governmentId' : IDL.Null,
  });
  const DocumentRecord = IDL.Record({
    'uploadStatus' : UploadStatus,
    'userId' : UserId,
    'storageRef' : IDL.Opt(ExternalBlob),
    'docType' : DocumentType,
    'uploadedAt' : IDL.Opt(Timestamp),
  });
  const IndividualMizanRecord = IDL.Record({
    'completedAt' : IDL.Opt(Timestamp),
    'narrativeSummary' : IDL.Text,
    'overallScore' : IDL.Nat,
    'incomeStabilityScore' : IDL.Nat,
    'debtBehaviorScore' : IDL.Nat,
    'stage' : IDL.Variant({ 'full' : IDL.Null, 'preliminary' : IDL.Null }),
    'borderlineFlag' : IDL.Bool,
    'repaymentCapacityScore' : IDL.Nat,
    'riskLevel' : RiskLevel__1,
  });
  const IndividualTawthiqRecord = IDL.Record({
    'completedAt' : IDL.Opt(Timestamp),
    'watchlistClean' : IDL.Bool,
    'narrativeSummary' : IDL.Text,
    'creditReadiness' : IDL.Variant({
      'conditionalReady' : IDL.Null,
      'notReady' : IDL.Null,
      'ready' : IDL.Null,
    }),
    'shariaComplianceScore' : IDL.Nat,
    'bvnVerified' : IDL.Bool,
    'ninVerified' : IDL.Bool,
    'shariaFlags' : IDL.Vec(IDL.Text),
    'incomeAnalysis' : IDL.Text,
  });
  const IncomeSource = IDL.Variant({
    'other' : IDL.Null,
    'employment' : IDL.Null,
    'selfEmployment' : IDL.Null,
    'business' : IDL.Null,
  });
  const PreferredInstrument = IDL.Variant({
    'murabaha' : IDL.Null,
    'istisna' : IDL.Null,
    'other' : IDL.Null,
    'ijarah' : IDL.Null,
    'salam' : IDL.Null,
    'musharakah' : IDL.Null,
    'mudarabah' : IDL.Null,
  });
  const EmploymentStatus = IDL.Variant({
    'unemployed' : IDL.Null,
    'employed' : IDL.Null,
    'student' : IDL.Null,
    'selfEmployed' : IDL.Null,
  });
  const FinancingPurpose = IDL.Variant({
    'other' : IDL.Null,
    'education' : IDL.Null,
    'startupCapital' : IDL.Null,
    'homePurchase' : IDL.Null,
    'vehicle' : IDL.Null,
    'medical' : IDL.Null,
  });
  const IndividualProfile = IDL.Record({
    'id' : UserId,
    'bvn' : IDL.Text,
    'nin' : IDL.Text,
    'mizanRecord' : IDL.Opt(IndividualMizanRecord),
    'occupation' : IDL.Text,
    'termsAcceptedAt' : IDL.Opt(Timestamp),
    'financingPurposeOther' : IDL.Opt(IDL.Text),
    'dateOfBirth' : IDL.Text,
    'tawthiqRecord' : IDL.Opt(IndividualTawthiqRecord),
    'createdAt' : Timestamp,
    'incomeSource' : IncomeSource,
    'fullName' : IDL.Text,
    'accountClosureRequestedAt' : IDL.Opt(Timestamp),
    'photoUrl' : IDL.Opt(IDL.Text),
    'amountSought' : IDL.Nat,
    'preferredInstrument' : PreferredInstrument,
    'kycRecord' : IDL.Opt(KycCheckRecord),
    'updatedAt' : Timestamp,
    'employerName' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'employmentStatus' : EmploymentStatus,
    'registrationStatus' : RegistrationStatus,
    'bankLinkStatus' : BankLinkStatus,
    'financingPurpose' : FinancingPurpose,
    'accountClosureRequested' : IDL.Bool,
    'monthlyIncome' : IDL.Nat,
  });
  const Result_5 = IDL.Variant({ 'ok' : IndividualProfile, 'err' : IDL.Text });
  const KashifReportLog = IDL.Record({
    'businessId' : IDL.Principal,
    'generatedAt' : IDL.Int,
    'viewCount' : IDL.Nat,
    'lastViewedAt' : IDL.Opt(IDL.Int),
  });
  const BusinessPage = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(BusinessProfile),
  });
  const FinancierType = IDL.Variant({
    'institution' : IDL.Null,
    'group' : IDL.Null,
    'individual' : IDL.Null,
  });
  const InstitutionDetails = IDL.Record({
    'riskAppetite' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'preferredInstruments' : IDL.Vec(PreferredInstrument),
    'ticketSizeMax' : IDL.Nat,
    'ticketSizeMin' : IDL.Nat,
  });
  const GroupDetails = IDL.Record({
    'numberOfMembers' : IDL.Nat,
    'leadContactBvn' : IDL.Text,
    'leadContactNin' : IDL.Text,
    'combinedInvestmentCapacity' : IDL.Nat,
    'legalBasis' : IDL.Text,
    'riskAppetite' : IDL.Text,
    'preferredInstruments' : IDL.Vec(PreferredInstrument),
    'leadContactName' : IDL.Text,
    'groupName' : IDL.Text,
  });
  const IndividualDetails = IDL.Record({
    'bvn' : IDL.Text,
    'nin' : IDL.Text,
    'occupation' : IDL.Text,
    'investmentCapacity' : IDL.Nat,
    'fullName' : IDL.Text,
    'riskAppetite' : IDL.Text,
    'preferredInstruments' : IDL.Vec(PreferredInstrument),
  });
  const FinancierStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
    'PendingReview' : IDL.Null,
  });
  const FinancierProfile = IDL.Record({
    'financierType' : IDL.Opt(FinancierType),
    'institutionDetails' : IDL.Opt(InstitutionDetails),
    'groupDetails' : IDL.Opt(GroupDetails),
    'institutionName' : IDL.Text,
    'individualDetails' : IDL.Opt(IndividualDetails),
    'userId' : UserId,
    'createdAt' : Timestamp,
    'contactPerson' : IDL.Text,
    'areasOfFinancing' : IDL.Vec(IDL.Text),
    'photoUrl' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'financierStatus' : FinancierStatus,
    'licenseNumber' : IDL.Text,
    'phone' : IDL.Text,
    'registrationStatus' : RegistrationStatus,
  });
  const FinancierPage = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(FinancierProfile),
  });
  const IndividualSummary = IDL.Record({
    'id' : UserId,
    'createdAt' : Timestamp,
    'fullName' : IDL.Text,
    'amountSought' : IDL.Nat,
    'registrationStatus' : RegistrationStatus,
    'financingPurpose' : FinancingPurpose,
    'riskLevel' : RiskLevel__1,
  });
  const Result_8 = IDL.Variant({
    'ok' : IDL.Record({
      'total' : IDL.Nat,
      'items' : IDL.Vec(IndividualSummary),
    }),
    'err' : IDL.Text,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const AccountClosureRequest = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'applicantType' : IDL.Variant({
      'business' : IDL.Null,
      'financier' : IDL.Null,
      'individual' : IDL.Null,
    }),
    'requestId' : IDL.Text,
    'processedAt' : IDL.Opt(Timestamp),
    'adminNote' : IDL.Opt(IDL.Text),
    'principalId' : UserId,
    'requestedAt' : Timestamp,
  });
  const Result_7 = IDL.Variant({
    'ok' : IDL.Record({
      'total' : IDL.Nat,
      'items' : IDL.Vec(AccountClosureRequest),
    }),
    'err' : IDL.Text,
  });
  const AdminAnalytics = IDL.Record({
    'averageMizanScore' : IDL.Nat,
    'closedDealsCount' : IDL.Nat,
    'financingReadyCount' : IDL.Nat,
    'tawthiqPassCount' : IDL.Nat,
    'pendingReviewCount' : IDL.Nat,
    'totalFinanciers' : IDL.Nat,
    'totalIndividuals' : IDL.Nat,
    'tawthiqConditionalCount' : IDL.Nat,
    'tawthiqFailCount' : IDL.Nat,
    'activeFinancierCount' : IDL.Nat,
    'totalBusinesses' : IDL.Nat,
  });
  const Result_6 = IDL.Variant({ 'ok' : AdminAnalytics, 'err' : IDL.Text });
  const AuditEntry = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'oldValue' : IDL.Opt(IDL.Text),
    'changedBy' : IDL.Text,
    'newValue' : IDL.Opt(IDL.Text),
    'entityId' : IDL.Text,
    'timestamp' : Timestamp,
    'entityType' : IDL.Text,
    'reason' : IDL.Opt(IDL.Text),
  });
  const AuditPage = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'entries' : IDL.Vec(AuditEntry),
  });
  const ApplicantType = IDL.Variant({
    'business' : IDL.Null,
    'individual' : IDL.Null,
  });
  const CompatibilityResult = IDL.Record({
    'halalComplianceScore' : IDL.Nat,
    'applicantType' : ApplicantType,
    'compatibilityScore' : IDL.Nat,
    'businessCategory' : IDL.Text,
    'displayName' : IDL.Text,
    'businessId' : IDL.Principal,
    'financingTypes' : IDL.Vec(IDL.Text),
    'riskLevel' : RiskLevel,
  });
  const MaskedCredentials = IDL.Record({
    'monoSecretKey' : IDL.Text,
    'twilioAuthToken' : IDL.Text,
    'twilioAccountSid' : IDL.Text,
    'openAiApiKey' : IDL.Text,
    'twilioWhatsappFrom' : IDL.Text,
  });
  const DealReport = IDL.Record({
    'applicantType' : ApplicantType,
    'creditReadiness' : IDL.Text,
    'compatibilityScore' : IDL.Nat,
    'financingRecommendation' : IDL.Text,
    'riskBreakdown' : IDL.Text,
    'generatedAt' : IDL.Int,
    'mizanVersion' : IDL.Int,
    'executiveSummary' : IDL.Text,
    'tawthiqVersion' : IDL.Int,
    'financialHighlights' : IDL.Text,
    'suggestedFinancingStructure' : IDL.Text,
    'shariahComplianceStatus' : IDL.Text,
  });
  const KashifScoringConfig = IDL.Record({
    'riskKeywords' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'instrumentWeights' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'defaultScore' : IDL.Nat,
  });
  const NotificationRecord = IDL.Record({
    'statusChange' : IDL.Text,
    'recipientPhone' : IDL.Text,
    'sentAt' : Timestamp,
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const Result_4 = IDL.Variant({
    'ok' : IDL.Record({
      'total' : IDL.Nat,
      'items' : IDL.Vec(NotificationRecord),
    }),
    'err' : IDL.Text,
  });
  const AppealStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const TawthiqAppeal = IDL.Record({
    'id' : IDL.Text,
    'status' : AppealStatus,
    'documentName' : IDL.Opt(IDL.Text),
    'documentUrl' : IDL.Opt(IDL.Text),
    'adminPrincipal' : IDL.Opt(IDL.Principal),
    'businessId' : UserId,
    'flagId' : IDL.Text,
    'submittedAt' : Timestamp,
    'reviewedAt' : IDL.Opt(Timestamp),
    'adminNote' : IDL.Opt(IDL.Text),
    'appealText' : IDL.Text,
  });
  const PipelineStage = IDL.Variant({
    'dueDiligence' : IDL.Null,
    'closed' : IDL.Null,
    'offerSent' : IDL.Null,
    'reviewing' : IDL.Null,
  });
  const ShortlistEntry = IDL.Record({
    'businessId' : IDL.Principal,
    'addedAt' : IDL.Int,
  });
  const TawthiqOverviewStats = IDL.Record({
    'pendingCount' : IDL.Nat,
    'conditionalCount' : IDL.Nat,
    'totalProcessed' : IDL.Nat,
    'notReadyCount' : IDL.Nat,
    'passedCount' : IDL.Nat,
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const Message = IDL.Record({
    'applicantId' : IDL.Text,
    'messageId' : IDL.Nat,
    'isRead' : IDL.Bool,
    'messageText' : IDL.Text,
    'timestamp' : IDL.Int,
    'financierId' : IDL.Text,
    'recipientId' : IDL.Principal,
    'senderId' : IDL.Principal,
  });
  const DirectMessageThread = IDL.Record({
    'lastMessageAt' : IDL.Int,
    'messages' : IDL.Vec(Message),
    'participantIds' : IDL.Vec(IDL.Principal),
    'threadId' : IDL.Text,
  });
  const ProfilePrivacySettings = IDL.Record({
    'applicantId' : IDL.Text,
    'showFinancingAmount' : IDL.Bool,
    'showMizanScore' : IDL.Bool,
    'showDirectorNames' : IDL.Bool,
    'showIncome' : IDL.Bool,
  });
  const PublicApplicantProfile = IDL.Record({
    'applicantId' : IDL.Text,
    'fullName' : IDL.Text,
    'amountSought' : IDL.Opt(IDL.Nat),
    'mizanScore' : IDL.Opt(IDL.Nat),
    'preferredInstrument' : IDL.Text,
    'registrationStatus' : IDL.Text,
    'financingPurpose' : IDL.Text,
    'monthlyIncome' : IDL.Opt(IDL.Nat),
  });
  const InviteLinkRecord = IDL.Record({
    'status' : IDL.Text,
    'expiresAt' : IDL.Int,
    'code' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'financier' : IDL.Null,
    'businessApplicant' : IDL.Null,
  });
  const ApplicantSummary = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : UserId,
    'role' : UserRole,
    'halalComplianceStatus' : HalalComplianceStatus,
    'financingReady' : IDL.Bool,
    'financingReadyScore' : IDL.Nat,
    'riskLevel' : RiskLevel__1,
  });
  const Page = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(ApplicantSummary),
  });
  const Result_3 = IDL.Variant({
    'ok' : IDL.Record({
      'status' : RegistrationStatus,
      'tawthiqDone' : IDL.Bool,
      'mizanDone' : IDL.Bool,
    }),
    'err' : IDL.Text,
  });
  const CredentialsSettings = IDL.Record({
    'monoSecretKey' : IDL.Text,
    'twilioAuthToken' : IDL.Text,
    'twilioAccountSid' : IDL.Text,
    'openAiApiKey' : IDL.Text,
    'twilioWhatsappFrom' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const BusinessProfileUpdate = IDL.Record({
    'contactPerson' : IDL.Opt(IDL.Text),
    'businessName' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adminChangeIndividualStatus' : IDL.Func(
        [UserId, RegistrationStatus],
        [Result],
        [],
      ),
    'adminGetBusiness' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(BusinessProfile)],
        [],
      ),
    'adminGetDocumentsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DocumentRecord)],
        [],
      ),
    'adminGetIndividual' : IDL.Func([UserId], [Result_5], []),
    'adminGetKashifLogs' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Record({ 'total' : IDL.Nat, 'items' : IDL.Vec(KashifReportLog) })],
        [],
      ),
    'adminListBusinesses' : IDL.Func([IDL.Nat, IDL.Nat], [BusinessPage], []),
    'adminListFinanciers' : IDL.Func([IDL.Nat, IDL.Nat], [FinancierPage], []),
    'adminListIndividuals' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [Result_8],
        ['query'],
      ),
    'adminProcessAccountClosure' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Text],
        [Result],
        [],
      ),
    'adminSetFinancingReady' : IDL.Func(
        [IDL.Principal, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'adminSetIndividualFinancingReady' : IDL.Func([UserId], [Result], []),
    'adminTriggerReportRegeneration' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'bootstrapAdmin' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'generateAdminInviteLink' : IDL.Func([], [Result_1], []),
    'getAccountClosureRequests' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [Result_7],
        ['query'],
      ),
    'getAdminAnalytics' : IDL.Func([], [Result_6], ['query']),
    'getAdminCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAuditLog' : IDL.Func([IDL.Nat, IDL.Nat], [AuditPage], ['query']),
    'getAuditLogForEntity' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [AuditPage],
        ['query'],
      ),
    'getBootstrapAdmin' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getComparisonData' : IDL.Func(
        [IDL.Vec(IDL.Principal)],
        [
          IDL.Variant({
            'ok' : IDL.Vec(CompatibilityResult),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getCredentials' : IDL.Func([], [MaskedCredentials], ['query']),
    'getCycleBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getDealReport' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : DealReport, 'err' : IDL.Text })],
        [],
      ),
    'getDocumentsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DocumentRecord)],
        ['query'],
      ),
    'getFinancingReadyBusiness' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(BusinessProfile)],
        ['query'],
      ),
    'getKashifScoringConfig' : IDL.Func([], [KashifScoringConfig], ['query']),
    'getMatchedBorrowers' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'items' : IDL.Vec(CompatibilityResult),
          }),
        ],
        [],
      ),
    'getMizanResult' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : MizanRecord, 'err' : IDL.Text })],
        ['query'],
      ),
    'getMockCycleBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyBusinessProfile' : IDL.Func(
        [],
        [IDL.Opt(BusinessProfile)],
        ['query'],
      ),
    'getMyDocument' : IDL.Func(
        [DocumentType],
        [IDL.Opt(DocumentRecord)],
        ['query'],
      ),
    'getMyFinancierProfile' : IDL.Func(
        [],
        [IDL.Opt(FinancierProfile)],
        ['query'],
      ),
    'getMyIndividualProfile' : IDL.Func([], [Result_5], ['query']),
    'getMyNotifications' : IDL.Func([IDL.Nat, IDL.Nat], [Result_4], ['query']),
    'getMyTawthiqAppeals' : IDL.Func([], [IDL.Vec(TawthiqAppeal)], ['query']),
    'getPipeline' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, PipelineStage))],
        ['query'],
      ),
    'getPreliminaryMizanByBusiness' : IDL.Func(
        [UserId],
        [IDL.Opt(MizanRecord)],
        ['query'],
      ),
    'getPreliminaryMizanResult' : IDL.Func(
        [],
        [IDL.Opt(MizanRecord)],
        ['query'],
      ),
    'getProfilePhoto' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getShortlist' : IDL.Func([], [IDL.Vec(ShortlistEntry)], []),
    'getStableStateVersion' : IDL.Func([], [IDL.Nat], ['query']),
    'getTawthiqAdminNote' : IDL.Func([UserId], [IDL.Opt(IDL.Text)], ['query']),
    'getTawthiqAppeals' : IDL.Func(
        [UserId],
        [IDL.Vec(TawthiqAppeal)],
        ['query'],
      ),
    'getTawthiqCompletedAssessments' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [
          IDL.Record({
            'page' : IDL.Nat,
            'totalCount' : IDL.Nat,
            'pageSize' : IDL.Nat,
            'items' : IDL.Vec(BusinessProfile),
          }),
        ],
        ['query'],
      ),
    'getTawthiqOverviewStats' : IDL.Func([], [TawthiqOverviewStats], ['query']),
    'getTawthiqPendingReviews' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [
          IDL.Record({
            'page' : IDL.Nat,
            'totalCount' : IDL.Nat,
            'pageSize' : IDL.Nat,
            'items' : IDL.Vec(BusinessProfile),
          }),
        ],
        ['query'],
      ),
    'getTawthiqRecord' : IDL.Func(
        [UserId],
        [IDL.Opt(TawthiqRecord)],
        ['query'],
      ),
    'getUnreadNotificationCount' : IDL.Func([], [Result_2], ['query']),
    'get_my_threads' : IDL.Func([], [IDL.Vec(DirectMessageThread)], ['query']),
    'get_privacy_settings' : IDL.Func(
        [IDL.Text],
        [ProfilePrivacySettings],
        ['query'],
      ),
    'get_public_profile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PublicApplicantProfile)],
        ['query'],
      ),
    'get_thread_messages' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'get_unread_count' : IDL.Func([], [IDL.Nat], ['query']),
    'isAdminBootstrapped' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkBankAccount' : IDL.Func([IDL.Text], [BusinessProfile], []),
    'listAdminInviteLinks' : IDL.Func(
        [],
        [IDL.Vec(InviteLinkRecord)],
        ['query'],
      ),
    'listBorderlineBusinesses' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'items' : IDL.Vec(ApplicantSummary),
          }),
        ],
        ['query'],
      ),
    'listFinancingReadyApplicants' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [Page],
        ['query'],
      ),
    'listMyDocuments' : IDL.Func([], [IDL.Vec(DocumentRecord)], ['query']),
    'markNotificationsRead' : IDL.Func([], [Result], []),
    'mark_messages_read' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'mockTopUp' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'pollIndividualStatus' : IDL.Func([], [Result_3], ['query']),
    'redeemAdminInviteLink' : IDL.Func([IDL.Text], [Result], []),
    'registerAsFinancier' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          FinancierType,
          IDL.Opt(InstitutionDetails),
          IDL.Opt(IndividualDetails),
          IDL.Opt(GroupDetails),
        ],
        [FinancierProfile],
        [],
      ),
    'removeFromShortlist' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'removePipelineEntry' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'requestAccountClosure' : IDL.Func([], [Result], []),
    'requestIndividualBankLink' : IDL.Func([], [Result_1], []),
    'reviewTawthiqAppeal' : IDL.Func(
        [UserId, IDL.Text, AppealStatus, IDL.Text],
        [IDL.Variant({ 'ok' : TawthiqAppeal, 'err' : IDL.Text })],
        [],
      ),
    'revokeAdminInviteLink' : IDL.Func([IDL.Text], [Result], []),
    'runAndStorePreliminaryMizan' : IDL.Func([IDL.Principal], [], []),
    'saveTawthiqAdminNote' : IDL.Func(
        [UserId, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'send_message' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal, IDL.Text],
        [Result_2],
        [],
      ),
    'setCredentials' : IDL.Func([CredentialsSettings], [], []),
    'setFinancierStatus' : IDL.Func(
        [IDL.Principal, FinancierStatus, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setPipelineStage' : IDL.Func(
        [IDL.Principal, PipelineStage],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setProfilePhoto' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'shortlistBorrower' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'submitBusinessRegistrationWithKyc' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(DirectorRecord),
          IDL.Opt(ProprietorRecord),
        ],
        [BusinessProfile],
        [],
      ),
    'submitIndividualRegistration' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          EmploymentStatus,
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IncomeSource,
          FinancingPurpose,
          IDL.Opt(IDL.Text),
          IDL.Nat,
          PreferredInstrument,
          IDL.Opt(Timestamp),
        ],
        [Result_1],
        [],
      ),
    'submitTawthiqAppeal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : TawthiqAppeal, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'triggerMizanAnalysis' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : MizanRecord, 'err' : IDL.Text })],
        [],
      ),
    'updateBusinessProfile' : IDL.Func(
        [IDL.Principal, BusinessProfileUpdate],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateBusinessStatus' : IDL.Func(
        [IDL.Principal, RegistrationStatus, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateIndividualProfile' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IncomeSource),
        ],
        [Result],
        [],
      ),
    'updateKashifScoringConfig' : IDL.Func(
        [KashifScoringConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateMyProfile' : IDL.Func(
        [BusinessProfileUpdate],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'update_privacy_settings' : IDL.Func(
        [IDL.Text, ProfilePrivacySettings],
        [Result],
        [],
      ),
    'uploadDocument' : IDL.Func(
        [DocumentType, ExternalBlob],
        [DocumentRecord],
        [],
      ),
    'validateAdminInviteLink' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };