/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountClosureRequest {
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'applicantType' : { 'business' : null } |
    { 'financier' : null } |
    { 'individual' : null },
  'requestId' : string,
  'processedAt' : [] | [Timestamp],
  'adminNote' : [] | [string],
  'principalId' : UserId,
  'requestedAt' : Timestamp,
}
export interface AdminAnalytics {
  'averageMizanScore' : bigint,
  'closedDealsCount' : bigint,
  'financingReadyCount' : bigint,
  'tawthiqPassCount' : bigint,
  'pendingReviewCount' : bigint,
  'totalFinanciers' : bigint,
  'totalIndividuals' : bigint,
  'tawthiqConditionalCount' : bigint,
  'tawthiqFailCount' : bigint,
  'activeFinancierCount' : bigint,
  'totalBusinesses' : bigint,
}
export type AppealStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface ApplicantSummary {
  'displayName' : string,
  'userId' : UserId,
  'role' : UserRole,
  'halalComplianceStatus' : HalalComplianceStatus,
  'financingReady' : boolean,
  'financingReadyScore' : bigint,
  'riskLevel' : RiskLevel__1,
}
export type ApplicantType = { 'business' : null } |
  { 'individual' : null };
export interface AuditEntry {
  'id' : string,
  'action' : string,
  'oldValue' : [] | [string],
  'changedBy' : string,
  'newValue' : [] | [string],
  'entityId' : string,
  'timestamp' : Timestamp,
  'entityType' : string,
  'reason' : [] | [string],
}
export interface AuditPage {
  'total' : bigint,
  'page' : bigint,
  'entries' : Array<AuditEntry>,
}
export interface BankLinkRecord {
  'status' : BankLinkStatus,
  'linkedAt' : [] | [Timestamp],
  'transactionSummary' : [] | [TransactionSummary],
  'balance' : [] | [bigint],
  'accountId' : [] | [string],
  'institutionName' : [] | [string],
  'currency' : [] | [string],
}
export type BankLinkStatus = { 'NotLinked' : null } |
  { 'Linked' : null } |
  { 'LinkFailed' : string };
export interface BusinessPage {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<BusinessProfile>,
}
export interface BusinessProfile {
  'mizanRecord' : [] | [MizanRecord],
  'cacNumber' : string,
  'proprietorDetails' : [] | [ProprietorRecord],
  'businessTypeEnum' : [] | [BusinessTypeEnum],
  'financingAmountSought' : [] | [bigint],
  'purposeOfFinancing' : [] | [string],
  'userId' : UserId,
  'tawthiqRecord' : [] | [TawthiqRecord],
  'createdAt' : Timestamp,
  'scoringRecord' : ScoringRecord,
  'halalComplianceStatus' : HalalComplianceStatus,
  'contactPerson' : string,
  'preliminaryMizanRecord' : [] | [MizanRecord],
  'businessName' : string,
  'businessType' : string,
  'photoUrl' : [] | [string],
  'financingReady' : boolean,
  'financingReadyScore' : bigint,
  'preferredInstrument' : [] | [string],
  'kycRecord' : KycCheckRecord,
  'yearOfIncorporation' : [] | [string],
  'address' : string,
  'phoneNumber' : string,
  'businessDescription' : [] | [string],
  'registrationStatus' : RegistrationStatus,
  'bankLinkRecord' : BankLinkRecord,
  'mizanDivergenceAlert' : boolean,
  'riskLevel' : RiskLevel__1,
  'annualRevenue' : bigint,
  'directorsList' : [] | [Array<DirectorRecord>],
}
export interface BusinessProfileUpdate {
  'contactPerson' : [] | [string],
  'businessName' : [] | [string],
  'address' : [] | [string],
  'phone' : [] | [string],
}
export type BusinessTypeEnum = { 'llc' : null } |
  { 'businessName' : null };
export interface CompatibilityResult {
  'halalComplianceScore' : bigint,
  'applicantType' : ApplicantType,
  'compatibilityScore' : bigint,
  'businessCategory' : string,
  'displayName' : string,
  'businessId' : Principal,
  'financingTypes' : Array<string>,
  'riskLevel' : RiskLevel,
}
export interface CredentialsSettings {
  'monoSecretKey' : string,
  'twilioAuthToken' : string,
  'twilioAccountSid' : string,
  'openAiApiKey' : string,
  'twilioWhatsappFrom' : string,
}
export type CreditReadinessVerdict = { 'conditionalReady' : null } |
  { 'notReady' : null } |
  { 'ready' : null };
export interface DealReport {
  'applicantType' : ApplicantType,
  'creditReadiness' : string,
  'compatibilityScore' : bigint,
  'financingRecommendation' : string,
  'riskBreakdown' : string,
  'generatedAt' : bigint,
  'mizanVersion' : bigint,
  'executiveSummary' : string,
  'tawthiqVersion' : bigint,
  'financialHighlights' : string,
  'suggestedFinancingStructure' : string,
  'shariahComplianceStatus' : string,
}
export interface DirectMessageThread {
  'lastMessageAt' : bigint,
  'messages' : Array<Message>,
  'participantIds' : Array<Principal>,
  'threadId' : string,
}
export interface DirectorRecord {
  'bvn' : string,
  'nin' : string,
  'nationality' : string,
  'directorName' : string,
  'ownershipPercentage' : number,
}
export interface DocumentRecord {
  'uploadStatus' : UploadStatus,
  'userId' : UserId,
  'storageRef' : [] | [ExternalBlob],
  'docType' : DocumentType,
  'uploadedAt' : [] | [Timestamp],
}
export type DocumentType = { 'cacCertificate' : null } |
  { 'bankStatement' : null } |
  { 'governmentId' : null };
export type EmploymentStatus = { 'unemployed' : null } |
  { 'employed' : null } |
  { 'student' : null } |
  { 'selfEmployed' : null };
export type ExternalBlob = Uint8Array;
export interface FinancierPage {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<FinancierProfile>,
}
export interface FinancierProfile {
  'financierType' : [] | [FinancierType],
  'institutionDetails' : [] | [InstitutionDetails],
  'groupDetails' : [] | [GroupDetails],
  'institutionName' : string,
  'individualDetails' : [] | [IndividualDetails],
  'userId' : UserId,
  'createdAt' : Timestamp,
  'contactPerson' : string,
  'areasOfFinancing' : Array<string>,
  'photoUrl' : [] | [string],
  'email' : string,
  'financierStatus' : FinancierStatus,
  'licenseNumber' : string,
  'phone' : string,
  'registrationStatus' : RegistrationStatus,
}
export type FinancierStatus = { 'Inactive' : null } |
  { 'Active' : null } |
  { 'PendingReview' : null };
export type FinancierType = { 'institution' : null } |
  { 'group' : null } |
  { 'individual' : null };
export type FinancingPurpose = { 'other' : null } |
  { 'education' : null } |
  { 'startupCapital' : null } |
  { 'homePurchase' : null } |
  { 'vehicle' : null } |
  { 'medical' : null };
export interface GroupDetails {
  'numberOfMembers' : bigint,
  'leadContactBvn' : string,
  'leadContactNin' : string,
  'combinedInvestmentCapacity' : bigint,
  'legalBasis' : string,
  'riskAppetite' : string,
  'preferredInstruments' : Array<PreferredInstrument>,
  'leadContactName' : string,
  'groupName' : string,
}
export type HalalComplianceStatus = { 'pending' : null } |
  { 'compliant' : null } |
  { 'flagged' : null };
export type IncomeSource = { 'other' : null } |
  { 'employment' : null } |
  { 'selfEmployment' : null } |
  { 'business' : null };
export interface InconsistencyFlag {
  'field' : string,
  'verifiedValue' : string,
  'declaredValue' : string,
}
export interface IndividualDetails {
  'bvn' : string,
  'nin' : string,
  'occupation' : string,
  'investmentCapacity' : bigint,
  'fullName' : string,
  'riskAppetite' : string,
  'preferredInstruments' : Array<PreferredInstrument>,
}
export interface IndividualMizanRecord {
  'completedAt' : [] | [Timestamp],
  'narrativeSummary' : string,
  'overallScore' : bigint,
  'incomeStabilityScore' : bigint,
  'debtBehaviorScore' : bigint,
  'stage' : { 'full' : null } |
    { 'preliminary' : null },
  'borderlineFlag' : boolean,
  'repaymentCapacityScore' : bigint,
  'riskLevel' : RiskLevel__1,
}
export interface IndividualProfile {
  'id' : UserId,
  'bvn' : string,
  'nin' : string,
  'mizanRecord' : [] | [IndividualMizanRecord],
  'occupation' : string,
  'termsAcceptedAt' : [] | [Timestamp],
  'financingPurposeOther' : [] | [string],
  'dateOfBirth' : string,
  'tawthiqRecord' : [] | [IndividualTawthiqRecord],
  'createdAt' : Timestamp,
  'incomeSource' : IncomeSource,
  'fullName' : string,
  'accountClosureRequestedAt' : [] | [Timestamp],
  'photoUrl' : [] | [string],
  'amountSought' : bigint,
  'preferredInstrument' : PreferredInstrument,
  'kycRecord' : [] | [KycCheckRecord],
  'updatedAt' : Timestamp,
  'employerName' : [] | [string],
  'address' : string,
  'employmentStatus' : EmploymentStatus,
  'registrationStatus' : RegistrationStatus,
  'bankLinkStatus' : BankLinkStatus,
  'financingPurpose' : FinancingPurpose,
  'accountClosureRequested' : boolean,
  'monthlyIncome' : bigint,
}
export interface IndividualSummary {
  'id' : UserId,
  'createdAt' : Timestamp,
  'fullName' : string,
  'amountSought' : bigint,
  'registrationStatus' : RegistrationStatus,
  'financingPurpose' : FinancingPurpose,
  'riskLevel' : RiskLevel__1,
}
export interface IndividualTawthiqRecord {
  'completedAt' : [] | [Timestamp],
  'watchlistClean' : boolean,
  'narrativeSummary' : string,
  'creditReadiness' : { 'conditionalReady' : null } |
    { 'notReady' : null } |
    { 'ready' : null },
  'shariaComplianceScore' : bigint,
  'bvnVerified' : boolean,
  'ninVerified' : boolean,
  'shariaFlags' : Array<string>,
  'incomeAnalysis' : string,
}
export interface InstitutionDetails {
  'riskAppetite' : string,
  'licenseNumber' : string,
  'preferredInstruments' : Array<PreferredInstrument>,
  'ticketSizeMax' : bigint,
  'ticketSizeMin' : bigint,
}
export interface InviteLinkRecord {
  'status' : string,
  'expiresAt' : bigint,
  'code' : string,
  'createdAt' : bigint,
}
export interface KashifReportLog {
  'businessId' : Principal,
  'generatedAt' : bigint,
  'viewCount' : bigint,
  'lastViewedAt' : [] | [bigint],
}
export interface KashifScoringConfig {
  'riskKeywords' : Array<[string, bigint]>,
  'instrumentWeights' : Array<[string, bigint]>,
  'defaultScore' : bigint,
}
export interface KycCheckRecord {
  'watchlistClean' : boolean,
  'cacVerified' : boolean,
  'watchlistParseError' : boolean,
  'kycStatus' : KycStatus,
  'creditScore' : bigint,
  'bvnVerified' : boolean,
  'ninVerified' : boolean,
  'tinVerified' : boolean,
  'verifiedAt' : [] | [Timestamp],
}
export type KycStatus = { 'Failed' : null } |
  { 'InProgress' : null } |
  { 'Verified' : null } |
  { 'Pending' : null };
export interface MaskedCredentials {
  'monoSecretKey' : string,
  'twilioAuthToken' : string,
  'twilioAccountSid' : string,
  'openAiApiKey' : string,
  'twilioWhatsappFrom' : string,
}
export interface Message {
  'applicantId' : string,
  'messageId' : bigint,
  'isRead' : boolean,
  'messageText' : string,
  'timestamp' : bigint,
  'financierId' : string,
  'recipientId' : Principal,
  'senderId' : Principal,
}
export interface MizanRecord {
  'halalComplianceScore' : bigint,
  'narrativeSummary' : string,
  'computedAt' : Timestamp,
  'incomeStabilityScore' : bigint,
  'riskClassification' : RiskLevel,
  'overallReadinessScore' : bigint,
  'debtBehaviorScore' : bigint,
  'stage' : MizanStage,
  'repaymentPatternScore' : bigint,
  'revenueTrendScore' : bigint,
  'isBorderline' : boolean,
  'borderlineReasons' : Array<string>,
}
export type MizanStage = { 'full' : null } |
  { 'preliminary' : null };
export interface NotificationRecord {
  'statusChange' : string,
  'recipientPhone' : string,
  'sentAt' : Timestamp,
  'message' : string,
  'success' : boolean,
}
export interface Page {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<ApplicantSummary>,
}
export type PipelineStage = { 'dueDiligence' : null } |
  { 'closed' : null } |
  { 'offerSent' : null } |
  { 'reviewing' : null };
export type PreferredInstrument = { 'murabaha' : null } |
  { 'istisna' : null } |
  { 'other' : null } |
  { 'ijarah' : null } |
  { 'salam' : null } |
  { 'musharakah' : null } |
  { 'mudarabah' : null };
export interface ProfilePrivacySettings {
  'applicantId' : string,
  'showFinancingAmount' : boolean,
  'showMizanScore' : boolean,
  'showDirectorNames' : boolean,
  'showIncome' : boolean,
}
export interface ProprietorRecord {
  'bvn' : string,
  'nin' : string,
  'proprietorName' : string,
}
export interface PublicApplicantProfile {
  'applicantId' : string,
  'fullName' : string,
  'amountSought' : [] | [bigint],
  'mizanScore' : [] | [bigint],
  'preferredInstrument' : string,
  'registrationStatus' : string,
  'financingPurpose' : string,
  'monthlyIncome' : [] | [bigint],
}
export type RegistrationStatus = { 'pending' : null } |
  { 'underReview' : null } |
  { 'financingReady' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'kycInProgress' : null };
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : string } |
  { 'err' : string };
export type Result_2 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_3 = {
    'ok' : {
      'status' : RegistrationStatus,
      'tawthiqDone' : boolean,
      'mizanDone' : boolean,
    }
  } |
  { 'err' : string };
export type Result_4 = {
    'ok' : { 'total' : bigint, 'items' : Array<NotificationRecord> }
  } |
  { 'err' : string };
export type Result_5 = { 'ok' : IndividualProfile } |
  { 'err' : string };
export type Result_6 = { 'ok' : AdminAnalytics } |
  { 'err' : string };
export type Result_7 = {
    'ok' : { 'total' : bigint, 'items' : Array<AccountClosureRequest> }
  } |
  { 'err' : string };
export type Result_8 = {
    'ok' : { 'total' : bigint, 'items' : Array<IndividualSummary> }
  } |
  { 'err' : string };
export type RiskLevel = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export type RiskLevel__1 = { 'low' : null } |
  { 'pending' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface ScoringRecord {
  'halalComplianceScore' : bigint,
  'scoredAt' : Timestamp,
  'scoringNotes' : string,
  'financingReadinessScore' : bigint,
  'riskLevel' : RiskLevel,
}
export interface ShariaFlag {
  'indicator' : string,
  'category' : string,
  'severity' : { 'major' : null } |
    { 'minor' : null },
}
export interface ShortlistEntry { 'businessId' : Principal, 'addedAt' : bigint }
export interface TawthiqAppeal {
  'id' : string,
  'status' : AppealStatus,
  'documentName' : [] | [string],
  'documentUrl' : [] | [string],
  'adminPrincipal' : [] | [Principal],
  'businessId' : UserId,
  'flagId' : string,
  'submittedAt' : Timestamp,
  'reviewedAt' : [] | [Timestamp],
  'adminNote' : [] | [string],
  'appealText' : string,
}
export interface TawthiqOverviewStats {
  'pendingCount' : bigint,
  'conditionalCount' : bigint,
  'totalProcessed' : bigint,
  'notReadyCount' : bigint,
  'passedCount' : bigint,
}
export interface TawthiqRecord {
  'completedAt' : [] | [Timestamp],
  'narrativeSummary' : string,
  'inconsistencyFlags' : Array<InconsistencyFlag>,
  'creditReadinessVerdict' : CreditReadinessVerdict,
  'shariaScreeningStatus' : { 'Failed' : null } |
    { 'Passed' : null } |
    { 'Pending' : null },
  'inconsistencyStatus' : { 'Flagged' : null } |
    { 'Clean' : null } |
    { 'Pending' : null },
  'shariaFlags' : Array<ShariaFlag>,
  'shariaScreeningNotes' : string,
}
export type Timestamp = bigint;
export interface TransactionSummary {
  'totalDebits' : bigint,
  'income' : bigint,
  'totalCredits' : bigint,
  'months' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UploadStatus = { 'uploaded' : null } |
  { 'notUploaded' : null };
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'financier' : null } |
  { 'businessApplicant' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'adminChangeIndividualStatus' : ActorMethod<
    [UserId, RegistrationStatus],
    Result
  >,
  'adminGetBusiness' : ActorMethod<[Principal], [] | [BusinessProfile]>,
  'adminGetDocumentsForUser' : ActorMethod<[Principal], Array<DocumentRecord>>,
  'adminGetIndividual' : ActorMethod<[UserId], Result_5>,
  'adminGetKashifLogs' : ActorMethod<
    [bigint, bigint],
    { 'total' : bigint, 'items' : Array<KashifReportLog> }
  >,
  'adminListBusinesses' : ActorMethod<[bigint, bigint], BusinessPage>,
  'adminListFinanciers' : ActorMethod<[bigint, bigint], FinancierPage>,
  'adminListIndividuals' : ActorMethod<[bigint, bigint], Result_8>,
  'adminProcessAccountClosure' : ActorMethod<[string, boolean, string], Result>,
  'adminSetFinancingReady' : ActorMethod<[Principal, boolean], boolean>,
  'adminSetIndividualFinancingReady' : ActorMethod<[UserId], Result>,
  'adminTriggerReportRegeneration' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'bootstrapAdmin' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'generateAdminInviteLink' : ActorMethod<[], Result_1>,
  'getAccountClosureRequests' : ActorMethod<[bigint, bigint], Result_7>,
  'getAdminAnalytics' : ActorMethod<[], Result_6>,
  'getAdminCount' : ActorMethod<[], bigint>,
  'getAuditLog' : ActorMethod<[bigint, bigint], AuditPage>,
  'getAuditLogForEntity' : ActorMethod<[string, bigint, bigint], AuditPage>,
  'getBootstrapAdmin' : ActorMethod<[], [] | [Principal]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getComparisonData' : ActorMethod<
    [Array<Principal>],
    { 'ok' : Array<CompatibilityResult> } |
      { 'err' : string }
  >,
  'getCredentials' : ActorMethod<[], MaskedCredentials>,
  'getCycleBalance' : ActorMethod<[], bigint>,
  'getDealReport' : ActorMethod<
    [Principal],
    { 'ok' : DealReport } |
      { 'err' : string }
  >,
  'getDocumentsForUser' : ActorMethod<[Principal], Array<DocumentRecord>>,
  'getFinancingReadyBusiness' : ActorMethod<
    [Principal],
    [] | [BusinessProfile]
  >,
  'getKashifScoringConfig' : ActorMethod<[], KashifScoringConfig>,
  'getMatchedBorrowers' : ActorMethod<
    [bigint, bigint],
    { 'total' : bigint, 'items' : Array<CompatibilityResult> }
  >,
  'getMizanResult' : ActorMethod<
    [Principal],
    { 'ok' : MizanRecord } |
      { 'err' : string }
  >,
  'getMockCycleBalance' : ActorMethod<[], bigint>,
  'getMyBusinessProfile' : ActorMethod<[], [] | [BusinessProfile]>,
  'getMyDocument' : ActorMethod<[DocumentType], [] | [DocumentRecord]>,
  'getMyFinancierProfile' : ActorMethod<[], [] | [FinancierProfile]>,
  'getMyIndividualProfile' : ActorMethod<[], Result_5>,
  'getMyNotifications' : ActorMethod<[bigint, bigint], Result_4>,
  'getMyTawthiqAppeals' : ActorMethod<[], Array<TawthiqAppeal>>,
  'getPipeline' : ActorMethod<[], Array<[Principal, PipelineStage]>>,
  'getPreliminaryMizanByBusiness' : ActorMethod<[UserId], [] | [MizanRecord]>,
  'getPreliminaryMizanResult' : ActorMethod<[], [] | [MizanRecord]>,
  'getProfilePhoto' : ActorMethod<[Principal], [] | [string]>,
  'getShortlist' : ActorMethod<[], Array<ShortlistEntry>>,
  'getStableStateVersion' : ActorMethod<[], bigint>,
  'getTawthiqAdminNote' : ActorMethod<[UserId], [] | [string]>,
  'getTawthiqAppeals' : ActorMethod<[UserId], Array<TawthiqAppeal>>,
  'getTawthiqCompletedAssessments' : ActorMethod<
    [bigint, bigint, [] | [string], [] | [string]],
    {
      'page' : bigint,
      'totalCount' : bigint,
      'pageSize' : bigint,
      'items' : Array<BusinessProfile>,
    }
  >,
  'getTawthiqOverviewStats' : ActorMethod<[], TawthiqOverviewStats>,
  'getTawthiqPendingReviews' : ActorMethod<
    [bigint, bigint],
    {
      'page' : bigint,
      'totalCount' : bigint,
      'pageSize' : bigint,
      'items' : Array<BusinessProfile>,
    }
  >,
  'getTawthiqRecord' : ActorMethod<[UserId], [] | [TawthiqRecord]>,
  'getUnreadNotificationCount' : ActorMethod<[], Result_2>,
  'get_my_threads' : ActorMethod<[], Array<DirectMessageThread>>,
  'get_privacy_settings' : ActorMethod<[string], ProfilePrivacySettings>,
  'get_public_profile' : ActorMethod<[string], [] | [PublicApplicantProfile]>,
  'get_thread_messages' : ActorMethod<[string, string], Array<Message>>,
  'get_unread_count' : ActorMethod<[], bigint>,
  'isAdminBootstrapped' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkBankAccount' : ActorMethod<[string], BusinessProfile>,
  'listAdminInviteLinks' : ActorMethod<[], Array<InviteLinkRecord>>,
  'listBorderlineBusinesses' : ActorMethod<
    [bigint],
    { 'total' : bigint, 'items' : Array<ApplicantSummary> }
  >,
  'listFinancingReadyApplicants' : ActorMethod<[bigint, bigint], Page>,
  'listMyDocuments' : ActorMethod<[], Array<DocumentRecord>>,
  'markNotificationsRead' : ActorMethod<[], Result>,
  'mark_messages_read' : ActorMethod<[string, string], Result>,
  'mockTopUp' : ActorMethod<[bigint], bigint>,
  'pollIndividualStatus' : ActorMethod<[], Result_3>,
  'redeemAdminInviteLink' : ActorMethod<[string], Result>,
  'registerAsFinancier' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      FinancierType,
      [] | [InstitutionDetails],
      [] | [IndividualDetails],
      [] | [GroupDetails],
    ],
    FinancierProfile
  >,
  'removeFromShortlist' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removePipelineEntry' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'requestAccountClosure' : ActorMethod<[], Result>,
  'requestIndividualBankLink' : ActorMethod<[], Result_1>,
  'reviewTawthiqAppeal' : ActorMethod<
    [UserId, string, AppealStatus, string],
    { 'ok' : TawthiqAppeal } |
      { 'err' : string }
  >,
  'revokeAdminInviteLink' : ActorMethod<[string], Result>,
  'runAndStorePreliminaryMizan' : ActorMethod<[Principal], undefined>,
  'saveTawthiqAdminNote' : ActorMethod<
    [UserId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'send_message' : ActorMethod<[string, string, Principal, string], Result_2>,
  'setCredentials' : ActorMethod<[CredentialsSettings], undefined>,
  'setFinancierStatus' : ActorMethod<
    [Principal, FinancierStatus, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setPipelineStage' : ActorMethod<
    [Principal, PipelineStage],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setProfilePhoto' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'shortlistBorrower' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'submitBusinessRegistrationWithKyc' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      string,
      Array<DirectorRecord>,
      [] | [ProprietorRecord],
    ],
    BusinessProfile
  >,
  'submitIndividualRegistration' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      EmploymentStatus,
      [] | [string],
      bigint,
      IncomeSource,
      FinancingPurpose,
      [] | [string],
      bigint,
      PreferredInstrument,
      [] | [Timestamp],
    ],
    Result_1
  >,
  'submitTawthiqAppeal' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    { 'ok' : TawthiqAppeal } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'triggerMizanAnalysis' : ActorMethod<
    [Principal],
    { 'ok' : MizanRecord } |
      { 'err' : string }
  >,
  'updateBusinessProfile' : ActorMethod<
    [Principal, BusinessProfileUpdate],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateBusinessStatus' : ActorMethod<
    [Principal, RegistrationStatus, [] | [string]],
    boolean
  >,
  'updateIndividualProfile' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [IncomeSource],
    ],
    Result
  >,
  'updateKashifScoringConfig' : ActorMethod<
    [KashifScoringConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateMyProfile' : ActorMethod<
    [BusinessProfileUpdate],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'update_privacy_settings' : ActorMethod<
    [string, ProfilePrivacySettings],
    Result
  >,
  'uploadDocument' : ActorMethod<[DocumentType, ExternalBlob], DocumentRecord>,
  'validateAdminInviteLink' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];